      - name: Build Debug APK
        run: |
          mkdir -p out
          ./gradlew :app_pojavlauncher:assembleDebug --warning-mode=none
          find app_pojavlauncher/build/outputs/apk -name "*.apk" | head -1 | xargs -I{} mv {} out/wither-launcher.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: wither-launcher
          path: out/wither-launcher.apk
